import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";
import { copyFileSync, mkdirSync, watch } from "node:fs";

// 插件发布所需的文件
const ASSETS = ["manifest.json", "styles.css"];

function copyDist() {
  mkdirSync("dist", { recursive: true });
  // main.js 为构建产物，与静态资源一并复制到 dist
  for (const file of ["main.js", ...ASSETS]) {
    copyFileSync(file, `dist/${file}`);
  }
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  await context.rebuild();
  copyDist();
  process.exit(0);
} else {
  // esbuild 0.28 的 context.watch() 不提供构建完成回调，
  // 因此改用 rebuild() + fs.watch 自行调度，统一在构建完成后同步 dist
  let timer: ReturnType<typeof setTimeout> | undefined;

  async function rebuildAndSync() {
    const result = await context.rebuild();
    if (result.errors.length === 0) copyDist();
  }

  function scheduleRebuild() {
    clearTimeout(timer);
    timer = setTimeout(rebuildAndSync, 100);
  }

  await rebuildAndSync();
  watch("src", { recursive: true }, scheduleRebuild);
  // 监听静态资源变化触发重新构建，以同步到 dist
  // 注意：不监听 main.js，避免构建产物写入引发循环重建
  for (const file of ASSETS) {
    watch(file, scheduleRebuild);
  }
}
